NotesBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: NotesBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        label:
            type: string
            length: 255
            unique: true
    oneToMany:
        notes:
            targetEntity: Note
            mappedBy: category
    lifecycleCallbacks: {  }
