# src/AppBundle/Resources/config/validation.yml

NotesBundle\Entity\Note:
    type: entity
    table: null
    repositoryClass: NotesBundle\Repository\NoteRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [title]
            errorpath: title
            message: 'error, identical title field.'
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '255'
            nullable: false
        content:
            type: string
            length: '255'
            nullable: false
        date:
            type: date
            length: '255'
            nullable: false
        category:
            type: string
            length: '255'
            nullable: false
    lifecycleCallbacks: {  }
