notes_homepage:
    path:     /
    defaults: { _controller: NotesBundle:Default:index }

createNote:
    path:  /createNote
    defaults: { _controller: NotesBundle:Default:createNote }

editNote:
    path:  /editNote/{id}
    defaults: { _controller: NotesBundle:Default:editNote }

deleteNote:
    path: /deleteNote/{id}
    defaults: { _controller: NotesBundle:Default:deleteNote }    

listCategories:
    path: /listCategories
    defaults: { _controller: NotesBundle:Default:listCategories }

createCategory:
    path: /createCategory
    defaults: { _controller: NotesBundle:Default:createCategory }

editCategory:
    path: /editCategory/{id}
    defaults: { _controller: NotesBundle:Default:editCategory }

deleteCategory:
    path: /deleteCategory/{id}
    defaults: { _controller: NotesBundle:Default:deleteCategory }    